openapi: 3.1.0
info:
  title: Car Dealership API
  description: API for managing car sales, employees, and users
  version: 1.0.0
components:
  schemas:
    $ref: './schemas.yaml' 

paths:
  /users:
    $ref: './paths/users.yaml' 

  /sales:
    $ref: './paths/sales.yaml' 

  /employees:
    $ref: './paths/employees.yaml'

  /customers:   
    $ref: './paths/customers.yaml'

  /cars:    
    $ref: './paths/cars.yaml'